services:
  iptv:
    image: ghq200101/iptv:latest
    container_name: iptv
    init: true
    ports:
      - "1905:1905"
    environment:
      - "mport=1905"
      - "mdataDir=/iptv/data"
      - "mhost=http://192.168.1.105:1905"
      # - "mpass=change-this-password"
      # - "mblank=true"
      # - "menableMigu=true"
      # - "menableBuiltInSources=true"
      # - "menableBuiltInSubscriptions=true"
      # - "mbrowserConcurrency=2"
    volumes:
      - "./data:/iptv/data"
    restart: always
